#!/bin/bash

echo $$ > alarm.pid

while true
do
    sleep 10
    fail=0

    config='config.js'
    if [ -f '../config.js' ]; then
        config='../config.js'
    fi

    gameCount=`grep exports.GameCount $config| awk '{print $3}' | awk -F';' '{print $1}'`
    serverId=`grep exports.ServerId $config| awk '{print $3}' | awk -F';' '{print $1}'`

    for (( c=1; c<=$gameCount; c++ ))
    do
        pidFile="game$c.pid"
        if [ ! -f $pidFile ]; then
            fail=1
        else
            pid=`cat $pidFile`
            if [ ! -d "/proc/${pid}" ]; then
                fail=1
            fi
        fi
    done


    if [ $fail -eq 1 ]; then
        if [ -f /usr/local/services/CloudDCAgent_L5-1.0/alarm/cloud_alarm ];then
            /usr/local/services/CloudDCAgent_L5-1.0/alarm/cloud_alarm 100712667 "error game $serverId"
        fi
    fi
    sleep 50
done
