#!/bin/bash
#
# manage gateway

prog="node"
options="--max-old-space-size=4000" #设置nodejs内测限制M
error_log="log/error.log"

RETVAL=0
_start() {
    # gateway gateway.js gateway.log

    name=$1
    args=$2
    logs=$3
    pidfile="$1.pid"

    echo -n $"start $name "
    if [ -f $pidfile ]; then
        echo -e "\E[31;40m[FAIL]\033[0m"
        echo "$name is Running"
    else
        $prog $args >>$logs 2>>$error_log &
        for i in {1..5}; do
            if [ -f $pidfile ]; then
                echo -e "\E[32;40m[OK]\033[0m"
                break
            else
                if [ $i -eq 5 ]; then
                    echo -e "\E[31;40m[FAIL]\033[0m"
                fi
            fi
            sleep 1
        done
    fi
    RETVAL=$?
}

_stop() {
    name=$1
    pidfile="$1.pid"

    echo -n $"stop $name "
    if [ -f ${pidfile} ]; then
        pid=`cat ${pidfile}`
        if [ -d "/proc/${pid}" ]; then
            while [ -d "/proc/${pid}" ]; do
                kill  ${pid}
                sleep 1
            done
        fi
        rm -f ${pidfile}
    fi
    echo -e "\E[32;40m[OK]\033[0m"
    RETVAL=$?
}
_reload() {
    echo $"Reloading nothing "
    RETVAL=$?
}

_status() {
    name=$1
    pidfile="$1.pid"
    
    echo -n -e "$name "
    if [ -f ${pidfile} ]; then
        pid=`cat ${pidfile}`
        if [ -d "/proc/${pid}" ]; then
            echo -e "\E[32;40m[Running]\033[0m"
        else
            echo -e "\E[31;40m[Lost]\033[0m"
        fi
    else
        echo -e "\E[31;40m[Stoped]\033[0m"
    fi

    RETVAL=$?
}

start() {
    _start gateway 'gateway.js' log/gateway.log
    
    pidfile='alarm_gateway.pid'
    echo -n $"start alarm "
    if [ -f $pidfile ]; then
        echo -e "\E[31;40m[FAIL]\033[0m"
        echo "alarm is Running"
    else
        ./alarm_gateway >/dev/null &
        echo -e "\E[32;40m[OK]\033[0m"
    fi
}

stop() {
    _stop alarm_gateway
    _stop gateway
}

status() {
    _status gateway
    _status alarm_gateway
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart)
        stop
        sleep 3
        start
        ;;
  reload)
        _reload
        ;;
  *)
        echo $"Usage: manage {start|stop|restart|status|reload}"
        exit 1
esac

exit $RETVAL
